import { Product } from './product.model';

export const DUMMY_PRODUCTS: Product[] = [
  { id: 1, name: 'Gaming Laptop', price: 1500, category: { id: 1, name: 'Laptops & Computers' }, stock: 12, imageUrl: './images/gaming_laptop.webp', description: 'A high-performance gaming laptop with RTX 3070.' },
  { id: 2, name: 'Desktop PC', price: 1200, category: { id: 1, name: 'Laptops & Computers' }, stock: 8, imageUrl: './images/desktop_pc.webp', description: 'A powerful desktop PC for work and gaming.' },
  { id: 3, name: 'Ultrabook', price: 1000, category: { id: 1, name: 'Laptops & Computers' }, stock: 15, imageUrl: './images/ultrabook.webp', description: 'A lightweight ultrabook for professionals.' },
  { id: 4, name: 'Wireless Mouse', price: 25, category: { id: 2, name: 'Computer Accessories' }, stock: 50, imageUrl: './images/wireless_mouse.webp', description: 'A sleek wireless mouse with ergonomic design.' },
  { id: 5, name: 'Mechanical Keyboard', price: 70, category: { id: 2, name: 'Computer Accessories' }, stock: 30, imageUrl: './images/mechanical_keyboard.webp', description: 'A mechanical keyboard with RGB lighting.' },
  { id: 6, name: 'Gaming Headset', price: 90, category: { id: 2, name: 'Computer Accessories' }, stock: 20, imageUrl: './images/gaming_headset.webp', description: 'A gaming headset with surround sound.' },
  { id: 7, name: '4K Monitor', price: 300, category: { id: 3, name: 'Monitors' }, stock: 10, imageUrl: './images/4k_monitor.webp', description: 'A 27-inch 4K UHD monitor.' },
  { id: 8, name: 'Gaming Monitor', price: 400, category: { id: 3, name: 'Monitors' }, stock: 8, imageUrl: './images/gaming_monitor.webp', description: 'A 32-inch gaming monitor with 144Hz refresh rate.' },
  { id: 9, name: 'Wi-Fi Router', price: 100, category: { id: 4, name: 'Networking Equipment' }, stock: 25, imageUrl: './images/wi-fi_router.webp', description: 'A dual-band Wi-Fi router with high speed.' },
  { id: 10, name: 'Network Switch', price: 50, category: { id: 4, name: 'Networking Equipment' }, stock: 30, imageUrl: './images/network_switch.webp', description: 'A 5-port gigabit network switch.' },
  { id: 11, name: 'External SSD', price: 150, category: { id: 5, name: 'Storage Devices' }, stock: 20, imageUrl: './images/external_ssd.webp', description: 'A 1TB external SSD for fast storage.' },
  { id: 12, name: 'USB Flash Drive', price: 20, category: { id: 5, name: 'Storage Devices' }, stock: 100, imageUrl: './images/usb_flash_drive.webp', description: 'A 128GB USB flash drive.' },
  { id: 13, name: 'Gaming Chair', price: 200, category: { id: 6, name: 'Gaming Gear' }, stock: 10, imageUrl: './images/gaming_chair.webp', description: 'An ergonomic gaming chair.' },
  { id: 14, name: 'Gaming Mouse', price: 50, category: { id: 6, name: 'Gaming Gear' }, stock: 40, imageUrl: './images/gaming_mouse.webp', description: 'A gaming mouse with customizable buttons.' },
  { id: 15, name: 'Windows 11 License', price: 120, category: { id: 7, name: 'Software & Licenses' }, stock: 50, imageUrl: './images/windows_11_license.webp', description: 'A genuine Windows 11 license.' },
  { id: 16, name: 'Antivirus Software', price: 40, category: { id: 7, name: 'Software & Licenses' }, stock: 100, imageUrl: './images/antivirus_software.webp', description: 'A 1-year antivirus subscription.' },
  { id: 17, name: 'Flagship Smartphone', price: 1000, category: { id: 8, name: 'Smartphones & Tablets' }, stock: 15, imageUrl: './images/flagship_smartphone.webp', description: 'A flagship smartphone with cutting-edge features.' },
  { id: 18, name: 'Budget Smartphone', price: 300, category: { id: 8, name: 'Smartphones & Tablets' }, stock: 25, imageUrl: './images/budget_smartphone.webp', description: 'A budget-friendly smartphone.' },
  { id: 19, name: 'Laptop Charger', price: 50, category: { id: 9, name: 'Power Supplies & Chargers' }, stock: 30, imageUrl: './images/laptop_charger.webp', description: 'A universal laptop charger.' },
  { id: 20, name: 'Portable Power Bank', price: 40, category: { id: 9, name: 'Power Supplies & Chargers' }, stock: 50, imageUrl: './images/portable_power_bank.webp', description: 'A 20,000mAh portable power bank.' },
  { id: 21, name: 'HDMI Cable', price: 15, category: { id: 10, name: 'Cables & Adapters' }, stock: 100, imageUrl: './images/hdmi_cable.webp', description: 'A 2-meter HDMI cable.' },
  { id: 22, name: 'USB-C Adapter', price: 10, category: { id: 10, name: 'Cables & Adapters' }, stock: 150, imageUrl: './images/usb-c_adapter.webp', description: 'A USB-C to USB-A adapter.' },
  { id: 23, name: 'Docking Station', price: 120, category: { id: 2, name: 'Computer Accessories' }, stock: 20, imageUrl: './images/docking_station.webp', description: 'A docking station for laptops.' },
  { id: 24, name: 'Webcam', price: 60, category: { id: 2, name: 'Computer Accessories' }, stock: 30, imageUrl: './images/webcam.webp', description: 'A full HD webcam for video calls.' },
  { id: 25, name: 'Graphics Card', price: 800, category: { id: 1, name: 'Laptops & Computers' }, stock: 5, imageUrl: './images/graphics_card.webp', description: 'A high-end graphics card for gaming and rendering.' },
  { id: 26, name: 'NAS Storage', price: 500, category: { id: 5, name: 'Storage Devices' }, stock: 10, imageUrl: './images/nas_storage.webp', description: 'A network-attached storage device.' },
  { id: 27, name: 'VR Headset', price: 400, category: { id: 6, name: 'Gaming Gear' }, stock: 8, imageUrl: './images/vr_headset.webp', description: 'A virtual reality headset for immersive gaming.' },
  { id: 28, name: 'Smartwatch', price: 250, category: { id: 8, name: 'Smartphones & Tablets' }, stock: 20, imageUrl: './images/smartwatch.webp', description: 'A smartwatch with fitness tracking.' },
  { id: 29, name: 'Thermal Paste', price: 10, category: { id: 2, name: 'Computer Accessories' }, stock: 100, imageUrl: './images/thermal_paste.webp', description: 'A high-quality thermal paste for CPUs.' },
  { id: 30, name: 'Surge Protector', price: 30, category: { id: 9, name: 'Power Supplies & Chargers' }, stock: 50, imageUrl: './images/surge_protector.webp', description: 'A surge protector with multiple outlets.' },
];